version: '3'

 
services:

         postgres: 
              container_name: drupal_db2
              image: postgres:9.6
              volumes:
                  - "drupal_vol:/var/www/html/sites"
              environment: 
                  - POSTGRES_PASSWORD=drupalpass
              networks:
                  - drupal_network

          
         web:
            container_name: drupal_www2
            image: drupal:v1
            ports: 
               -  "8080:80"
            networks:
              - drupal_network

volumes:
  drupal_vol:

networks:
 drupal_network:
            
